USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_OLTP_LOJA (@DATA_CARGA DATETIME)
AS 
BEGIN
     DELETE FROM TB_AUX_LOJA WHERE @DATA_CARGA = DATA_CARGA
	 INSERT INTO TB_AUX_LOJA(DATA_CARGA, COD_LOJA, LOJA, GERENTE,CIDADE,ESTADO, SIGLA_ESTADO)
	 SELECT @DATA_CARGA,L.COD_LOJA, L.NM_LOJA, F.NM_FUNCIONARIO, C.CIDADE, E.ESTADO, E.SIGLA FROM TB_LOJA L JOIN TB_FUNCIONARIO F ON(L.COD_GERENTE = F.COD_FUNCIONARIO) 
	 JOIN TB_CIDADE C ON(L.COD_CIDADE = C.COD_CIDADE) JOIN TB_ESTADO E ON(C.COD_ESTADO = E.COD_ESTADO)
	 
END
--TESTE
EXEC SP_OLTP_LOJA'20220929'
SELECT * FROM TB_AUX_LOJA
