USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_OLTP_FUNCIONARIO (@DATA_CARGA DATETIME)
AS 
BEGIN
     DELETE FROM TB_AUX_FUNCIONARIO WHERE @DATA_CARGA = DATA_CARGA
	 INSERT INTO TB_AUX_FUNCIONARIO(DATA_CARGA,COD_FUNCIONARIO,FUNCIONARIO,COD_CARGO,CARGO)
	 SELECT @DATA_CARGA, F.COD_FUNCIONARIO, F.NM_FUNCIONARIO, F.COD_CARGO, C.NM_CARGO FROM TB_FUNCIONARIO F JOIN TB_CARGO C 
	 ON(F.COD_CARGO = C.COD_CARGO)
	 

END

--TEM QUE TESTAR
EXEC SP_OLTP_FUNCIONARIO '20220929'
SELECT * FROM TB_AUX_FUNCIONARIO