USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_OLTP_LOJA (@DATA_CARGA DATETIME)
AS 
BEGIN
     DELETE FROM TB_AUX_PRODUTO WHERE @DATA_CARGA = DATA_CARGA
	 INSERT INTO TB_AUX_PRODUTO(DATA_CARGA, COD_PRODUTO, PRODUTO, COD_SUBCATEGORIA, SUBCATEGORIA, COD_CATEGORIA, CATEGORIA)
	 SELECT @DATA_CARGA, P.COD_PRODUTO, P.PRODUTO, S.COD_SUBCATEGORIA, S.SUBCATEGORIA, C.COD_CATEGORIA, C.CATEGORIA FROM TB_PRODUTO P JOIN TB_SUBCATEGORIA S ON(S.COD_SUBCATEGORIA = P.COD_SUBCATEGORIA) 
	 JOIN TB_CATEGORIA C ON(S.COD_CATEGORIA = C.COD_CATEGORIA) 
	 
END

EXEC SP_OLTP_LOJA '20220929'


