use bd_rede_postos

CREATE OR ALTER PROCEDURE SP_DIM_FUNCIONARIO (@DATA_CARGA DATETIME)
AS BEGIN
      DECLARE @DATACARGA DATETIME, @COD_FUNCIONARIO INT, @NM_FUNCIONARIO VARCHAR(100), @COD_CARGO INT, @NM_CARGO VARCHAR(100)
      DECLARE CURSOR_FUNCIONARIO CURSOR FOR SELECT A.DATA_CARGA, A.COD_FUNCIONARIO, A.FUNCIONARIO, A.COD_CARGO, A.CARGO FROM TB_AUX_FUNCIONARIO A
	  OPEN CURSOR_FUNCIONARIO
	  FETCH CURSOR_FUNCIONARIO INTO @DATACARGA, @COD_FUNCIONARIO, @NM_FUNCIONARIO, @COD_CARGO, @NM_CARGO

	  WHILE(@@FETCH_STATUS = 0)
	  BEGIN
	       IF EXISTS (SELECT * FROM DIM_FUNCIONARIO WHERE COD_FUNCIONARIO = @COD_FUNCIONARIO)
		   BEGIN
		        UPDATE DIM_FUNCIONARIO
				SET COD_CARGO = @COD_CARGO, @NM_CARGO = @NM_CARGO
				WHERE COD_FUNCIONARIO = @COD_FUNCIONARIO
		   END
		   ELSE
		       INSERT INTO DIM_FUNCIONARIO
			   VALUES(@COD_FUNCIONARIO, @NM_FUNCIONARIO, @COD_CARGO, @NM_CARGO)


		    FETCH CURSOR_FUNCIONARIO INTO @DATACARGA, @COD_FUNCIONARIO, @NM_FUNCIONARIO, @COD_CARGO, @NM_CARGO
	  END 
	  CLOSE CURSOR_FUNCIONARIO
	  DEALLOCATE CURSOR_FUNCIONARIO

END