USE bd_rede_postos

CREATE OR ALTER PROCEDURE SP_DIM_LOJA
AS BEGIN
       DECLARE @DATA_CARGA DATETIME, @COD_LOJA INT, @LOJA VARCHAR(100), @GERENTE VARCHAR(100), @CIDADE VARCHAR(100), @ESTADO VARCHAR(100), @SIGLA_ESTADO VARCHAR(2)
       DECLARE CURSOR_LOJA CURSOR FOR SELECT * FROM TB_AUX_LOJA
	   OPEN CURSOR_LOJA
	   FETCH CURSOR_LOJA INTO @COD_LOJA, @LOJA, @GERENTE, @CIDADE, @ESTADO, @SIGLA_ESTADO
	   WHILE(@@FETCH_STATUS = 0)
	   BEGIN
	       IF EXISTS (SELECT * FROM DIM_LOJA WHERE @COD_LOJA = COD_LOJA)
		   BEGIN
		       UPDATE DIM_LOJA
			   SET DT_FIM = @DATA_CARGA, FL_CORRENTE = 'NAO'
			   WHERE @COD_LOJA = COD_LOJA AND FL_CORRENTE = 'SIM'

			   INSERT INTO DIM_LOJA
			   VALUES(@COD_LOJA, @LOJA, @GERENTE, @CIDADE, @ESTADO, @SIGLA_ESTADO,@DATA_CARGA, NULL,'SIM')
		   END
		   ELSE 
		       INSERT INTO DIM_LOJA
			   VALUES(@COD_LOJA, @LOJA, @GERENTE, @CIDADE, @ESTADO, @SIGLA_ESTADO,@DATA_CARGA, NULL,'SIM')

	        FETCH CURSOR_LOJA INTO @COD_LOJA, @LOJA, @GERENTE, @CIDADE, @ESTADO, @SIGLA_ESTADO
	   END
	   CLOSE CURSOR_LOJA
	   DEALLOCATE CURSOR_LOJA


END